name: Build HW-WEAPON Decks

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Marp CLI
        uses: marp-team/marp-cli-action@v1
        with:
          generate_html: true
          generate_pdf: true
          args: --input-dir slides --output dist --allow-local-files

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
